name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - name: build
        run: zig build
      - name: test
        run: zig build test
